name: Deploy
on:
  push:
    branches:
      - master
jobs:
  qwq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
        persist-credentials: false

